### ISSUE TITLE
Hide the Livepatch and Language Support icons

### ISSUE THREAD

**Issue by locness3** [Cobweb-Aclevo/celos#11]
Livepatch `software-properties-livepatch.desktop` is accessible from Software&Updates, and Language Support `gnome-language-selector.desktop` is accessible from Settings. Hide them from the menu by overriding their desktop entry (in /usr/local)

**Comment by whyadamsalt** [comment]
Thank you, I will work on this!

**Comment by whyadamsalt** [comment]
Fixed in CelOS 1-beta6 (releasing later today)
