### ISSUE TITLE
Would there be a way to display a warning when a user tries to install an application through apt?

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Aclevo/celos#19]
Since Flatpak is the preferred package manager for CelOS, I feel like it would be beneficial for a warning to display inside of the terminal when an application is going to be installed through apt? 

Such as:
"It seems like you are going to be installing an application through apt, are you sure you want to do this? (Applications installed through apt are not protected by Flatpak sandboxing and the flatseal permissions manager)."

I personally feel like this should be possible with the alias command?

**Comment by TCr3** [comment]
not alias but a script
the script named apt would be somewhere like /usr/local/bin which is before /usr/bin in PATH, so it gets ran when you run apt
it would ask you that question and and run the real apt with the same arguments if you say yes
also this might be annoying for some users so it should be one time only

**Comment by locness3** [comment]
Hmmm.

**Comment by whyadamsalt** [comment]
> not alias but a script
> the script named apt would be somewhere like /usr/local/bin which is before /usr/bin in PATH, so it gets ran when you run apt
> it would ask you that question and and run the real apt with the same arguments if you say yes
> 
> also this might be annoying for some users so it should be a one time only (either by deleting itself on yes or saving the answer to a file)

It's an interesting point that you'd think it would be annoying. I suppose I would have to test this first before seeing whether it should appear in the final release. Thank you for your help!

**Comment by whyadamsalt** [comment]
For now, I have decided to close this issue as I do not feel like it would be very useful, as those installing from apt probably know what they are doing if they are not using the GUI methods available.
