### ISSUE TITLE
Change default shell to ZSH, use OMZ, Syntax Highlighting + Autosuggestions

### ISSUE THREAD

**Issue by whyadamsalt** [Cobweb-Aclevo/celos#20]
I want to make the default experience of CelOS as user friendly as possible. If possible I wish to change the default shell to ZSH with Oh-my-zsh installed. Furthermore I wish to include syntax highlighting and have autosuggestions for ZSH.

**Comment by whyadamsalt** [comment]
We have decided to leave the default as bash for now.

**Comment by ReasonablySelenium** [comment]
I can switch CelOS over to zsh/Oh-My-Zsh if this is re-opened.
