### ISSUE TITLE
Timed backgrounds

### ISSUE THREAD

**Issue by chairmantheboring** [Cobweb-Aclevo/celos#24]
Since we're making new backgrounds for CelOS, we should set up our default theme to include timed backgrounds like Adwaita. In Arch Linux, the file responsible for the shifting is `/usr/share/backgrounds/gnome/adwaita-timed.xml`. This file is also available [here](https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/blob/master/backgrounds/adwaita-timed.xml.in) in the repo for gnome backgrounds.

**Comment by whyadamsalt** [comment]
Okay, thank you!

What I am getting from this, is that I will have to purge items within `/usr/sharebackgrounds/` and then install gnome-backgrounds `sudo apt install gnome-backgrounds` after that I will need to clear the gnome default backgrounds from within the /usr/share/backgrounds/gnome directory, place our wallpapers in there, and then edit `adwaita-timed.xml`

**Comment by chairmantheboring** [comment]
Alternatively build your own package for the backgrounds. I don't think it would be so bad (famous last words to me), plus it would be significantly less hacky.

**Comment by whyadamsalt** [comment]
potentially, however after I've wrote my changes to `adwaita-timed.xml` it's only a matter of copying it into the ISO.

**Comment by whyadamsalt** [comment]
As of right now I do not feel like timed-backgrounds would be implemented to CelOS as it doesn't seem needed, however if someone was to open a pull request with a fully functioning `adwaita-timed.xml` I would not exclude it from the possibility of being included into the system.

- Adam Salt
